In [3]:
import numpy as np

arr = np.array([1,2,3,4]) #1D Array
arr2 = np.array([[1,2,3], [4,5,6]]) #2D Array
print(arr)
print(arr2)

#Unlike lists, all elements must have same data type

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
