In [1]:
import numpy as np

In [2]:
np.zeros((3,3)) #3rows, 3columns of zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2,4)) #2rows, 4columns of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.full((2,2), 7) #2rows, 2columns filled with 7

array([[7, 7],
       [7, 7]])

In [5]:
np.eye(4) # 4x4 identity matrix (An identity matrix, is a diagonal matrix with all its diagonal elements equal to 1 , and zeroes everywhere else)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.arange(1, 101, 2) #Creates arrays to a specific range. The third input specifies the gap between 2 numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [8]:
np.linspace(0,1,5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])