In [1]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
sum = np.sum(arr, axis=0) #Adds elements of column wise i.e 1 + 4 + 7

In [6]:
sum

array([ 6, 15, 24])

In [8]:
sum1 = np.sum(arr, axis=1)

In [9]:
sum1

array([ 6, 15, 24])