In [1]:
import numpy as np

arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [2]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
print(arr3D.shape)

(2, 2, 3)


In [4]:
print(arr3D[0, 1 , 2])

6


In [5]:
print(arr3D[:, 0 , :])

[[1 2 3]
 [7 8 9]]
