In [7]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [8]:
first_col = arr[:, 0]

In [9]:
print(first_col)

[1 4 7]


In [10]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [11]:
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [12]:
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
