In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

res = arr1 + arr2
print(res)

[11 22 33]


In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1 + arr2)

[[2 4 6]
 [5 7 9]]
