In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

In [5]:
flat = arr.flatten()

In [6]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [9]:
flat[3: 6]

array([4, 5, 6])

In [10]:
flat[:5] #prints first five elements

array([1, 2, 3, 4, 5])

In [11]:
flat[3:] #prints other elements except first 3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])