In [1]:
#Create a 3×3 array filled with random numbers and print its shape.
import numpy as np

arr = np.array([[10,20,30], [40,50,60],[70,80,90]])
print(arr)
print("Shape:", arr.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)


In [2]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr_float = np.array([1.1,2.2,3.3])
arr_int = arr_float.astype(np.int32)
print(arr_int)

[1 2 3]


In [4]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]

arr3 = np.array([1,2,3,4,5,6])
even_mask = arr3 % 2 == 0
even_arr = arr3[even_mask]
print(even_arr)

[2 4 6]


In [6]:
#Reshape a 1D array of size 9 into a 3×3 matrix
arr4 = np.array([1,2,3,4,5,6,7,8,9])
re_arr4 = arr4.reshape((3,3))
print(re_arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#Use boolean masking to filter numbers greater than 50 in an array.
bool_mask = arr > 50
print(arr[bool_mask])

[60 70 80 90]
